apiVersion: v1
kind: Service
metadata:
  name: bible-quiz-app
  labels:
    app: bible-quiz-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: bible-quiz-app
  type: NodePort