apiVersion: v1
kind: Service
metadata:
  name: bible-quiz-db
  labels:
    app: bible-quiz-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: bible-quiz-db
  type: ClusterIP