/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as HistoryRouteImport } from "./routes/history"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ResultAttemptIdRouteImport } from "./routes/result.$attemptId"
import { Route as QuizQuizIdRouteImport } from "./routes/quiz.$quizId"

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: "/result/$attemptId",
  path: "/result/$attemptId",
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: "/quiz/$quizId",
  path: "/quiz/$quizId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRoute
  "/history": typeof HistoryRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/quiz/$quizId": typeof QuizQuizIdRoute
  "/result/$attemptId": typeof ResultAttemptIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin": typeof AdminRoute
  "/history": typeof HistoryRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/quiz/$quizId": typeof QuizQuizIdRoute
  "/result/$attemptId": typeof ResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRoute
  "/history": typeof HistoryRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/quiz/$quizId": typeof QuizQuizIdRoute
  "/result/$attemptId": typeof ResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/history"
    | "/login"
    | "/register"
    | "/quiz/$quizId"
    | "/result/$attemptId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin"
    | "/history"
    | "/login"
    | "/register"
    | "/quiz/$quizId"
    | "/result/$attemptId"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/history"
    | "/login"
    | "/register"
    | "/quiz/$quizId"
    | "/result/$attemptId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/history": {
      id: "/history"
      path: "/history"
      fullPath: "/history"
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/result/$attemptId": {
      id: "/result/$attemptId"
      path: "/result/$attemptId"
      fullPath: "/result/$attemptId"
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/quiz/$quizId": {
      id: "/quiz/$quizId"
      path: "/quiz/$quizId"
      fullPath: "/quiz/$quizId"
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
